name: CI Pipeline

on:
  push:
    branches:
      - master
  
jobs:
  sast_scan: 
    name: SAST Bandit Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Latest Code
        uses: actions/checkout@v4.1.7

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit Scan
        run: |
          bandit -ll -ii -r . -f json -o bandit_results.json

      - name: Upload Bandit Results
        uses: actions/upload-artifact@v3.2.1-node20
        if: always()
        with:
          name: bandit_results
          path: bandit_results.json
        
  docker_scan:
    name: Docker Image Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Latest Code
        uses: actions/checkout@v4.1.7

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3.6.1
        with:
          version: '20.10.7'

      - name: Build Docker Image
        run: |
          docker build -f Dockerfile -t devsecops-pygoat:v1.0 .

      - name: Scan Docker Image Using Docker Scout
        uses: docker/scout-action@v1.13.0
        with:
          dockerhub-user: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          command: quickview,cves,recommendations      
          only-severities: high, critical
          sarif-file: scout_results.sarif

      - name: Upload Scout Results
        uses: actions/upload-artifact@v3.2.1-node20
        if: always()
        with:
          name: docker_scout_results
          path: scout_results.sarif
