name: CI Pipeline

on:
  push:
    branches:
      - master
  
jobs:
  sast_scan: 
    name: SAST Bandit Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Latest Code
        uses: actions/checkout@v4.1.7

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit Scan
        run: |
          bandit -ll -ii -r . -f json -o bandit_results.json

      - name: Upload Bandit Results
        uses: actions/upload-artifact@v3.2.1-node20
        if: always()
        with:
          name: bandit_results
          path: bandit_results.json

      
